export const COMPONENT_DATA = [
  {
    id: 1,
    title: 'Accordion',
    imageUrl: 'assets/images/tn/ids-accordion-tn@2x.png',
    imageLink: '#/components/accordion',
  },
  {
    id: 2,
    title: 'Action menu',
    imageUrl: 'assets/images/tn/ids-action-menu-tn@2x.png',
    imageLink: '#/components/action-menu',
  },
  {
    id: 3,
    title: 'Avatar',
    imageUrl: 'assets/images/tn/ids-avatar-tn@2x.png',
    imageLink: '#/components/avatar',
  },
  {
    id: 4,
    title: 'Button',
    imageUrl: 'assets/images/tn/ids-button-tn@2x.png',
    imageLink: '#/components/button',
  },
  {
    id: 5,
    title: 'Card',
    imageUrl: 'assets/images/tn/ids-card-tn@2x.png',
    imageLink: '#/components/card',
  },
  {
    id: 6,
    title: 'Checkbox',
    imageUrl: 'assets/images/tn/ids-checkbox-tn@2x.png',
    imageLink: '#/components/checkbox',
  },
  {
    id: 7,
    title: 'Chip',
    imageUrl: 'assets/images/tn/ids-chip-tn@2x.png',
    imageLink: '#/components/chip',
  },
  {
    id: 8,
    title: 'Dialog',
    imageUrl: 'assets/images/tn/ids-icon-dialog-tn@2x.png',
    imageLink: '#/components/dialog',
  },
  {
    id: 9,
    title: 'Divider',
    imageUrl: 'assets/images/tn/ids-divider-tn@2x.png',
    imageLink: '#/components/divider',
  },
  {
    id: 10,
    title: 'Fieldset',
    imageUrl: 'https://example.com/fieldset.png',
    imageLink: '#/components/fieldset',
  },
  {
    id: 11,
    title: 'Form field',
    imageUrl: 'assets/images/tn/ids-icon-form-field-tn@2x.png',
    imageLink: '#/components/form-field',
  },
  {
    id: 12,
    title: 'Icon',
    imageUrl: 'assets/images/tn/ids-icon-tn@2x.png',
    imageLink: '#/components/icon',
  },
  {
    id: 13,
    title: 'Icon button',
    imageUrl: 'assets/images/tn/ids-icon-button-tn@2x.png',
    imageLink: '#/components/icon-button',
  },
  {
    id: 14,
    title: 'Notification',
    imageUrl: 'assets/images/tn/ids-icon-notification-tn@2x.png',
    imageLink: '#/components/notification',
  },
  {
    id: 15,
    title: 'Overlay panel',
    imageUrl: 'assets/images/tn/ids-icon-overlay-tn@2x.png',
    imageLink: '#/components/overlay-panel',
  },
  {
    id: 16,
    title: 'Paginator',
    imageUrl: 'assets/images/tn/ids-icon-paginator-tn@2x.png',
    imageLink: '#/components/paginator',
  },
  {
    id: 17,
    title: 'Radio',
    imageUrl: 'assets/images/tn/ids-icon-radio-tn@2x.png',
    imageLink: '#/components/radio',
  },
  {
    id: 18,
    title: 'Scrollbar',
    imageUrl: 'https://example.com/scrollbar.png',
    imageLink: '#/components/scrollbar',
  },
  {
    id: 19,
    title: 'Segmented control',
    imageUrl: 'assets/images/tn/ids-icon-segmented-control-tn@2x.png',
    imageLink: '#/components/segmented-control',
  },
  {
    id: 20,
    title: 'Segmented control toggle',
    imageUrl: 'assets/images/tn/ids-icon-segmented-toogle-tn@2x.png',
    imageLink: '#/components/segmented-control-toggle',
  },
  {
    id: 21,
    title: 'Select',
    imageUrl: 'https://example.com/select.png',
    imageLink: '#/components/select',
  },
  {
    id: 22,
    title: 'Side navigation',
    imageUrl: 'https://example.com/side-nav.png',
    imageLink: '#/components/side-nav',
  },
  {
    id: 23,
    title: 'Snackbar',
    imageUrl: 'assets/images/tn/ids-icon-snackbar-tn@2x.png',
    imageLink: '#/components/snackbar',
  },
  {
    id: 24,
    title: 'Switch',
    imageUrl: 'assets/images/tn/ids-switch-tn@2x.png',
    imageLink: '#/components/switch',
  },
  {
    id: 25,
    title: 'Tab',
    imageUrl: 'assets/images/tn/ids-icon-tab-tn@2x.png',
    imageLink: '#/components/tab',
  },
  {
    id: 26,
    title: 'Tag',
    imageUrl: 'assets/images/tn/ids-icon-tag-tn@2x.png',
    imageLink: '#/components/tag',
  },
  {
    id: 27,
    title: 'Tooltip',
    imageUrl: 'assets/images/tn/ids-icon-tooltip-tn@2x.png',
    imageLink: '#/components/tooltip',
  },
];
