export const CONTENTCARD_LIST = [
  {
    id: 1,
    variant: 'surface',
    orientation: 'horizontal',
    aspectRatio: '16/9',
    imageBgColorVariant: 'light',
    imageURL: '../../../assets/images/illustration/ids-illu-comp-general@2x.png',
    imageCaption: 'this is a caption',
    overTitle: 'Breaking News',
    title: 'Angular Best Practices',
    description: 'Learn how to pass objects properly in Angular!',
    buttonOne: 'Read More',
    buttonTwo: 'Subscribe',
    state: 'do',
    transparent: true,
  },
  {
    id: 2,
    variant: 'surface',
    orientation: 'vertical',
    aspectRatio: '1/1',
    imageBgColorVariant: 'primary',
    overTitle: 'Tech Update',
    title: 'New Angular Features',
    description: 'Discover the latest features in Angular and how to use them effectively.',
    buttonOne: 'Explore',
    buttonTwo: 'Watch Video',
    // eslint-disable-next-line @stylistic/js/max-len
    imageURL: 'https://images.unsplash.com/photo-1595409583957-5d1ec5869de9?q=80&w=2486&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    state: 'dont',
  },
  {
    id: 3,
    orientation: 'horizontal',
    aspectRatio: '1/1',
    imageBgColorVariant: 'surface',
    overTitle: 'Tech Update',
    title: 'New Angular Features',
    description: 'Discover the latest features in Angular and how to use them effectively.',
    buttonOne: 'Explore',
    buttonTwo: 'Watch Video',
  },
  {
    id: 4,
    orientation: 'horizontal',
    title: 'hello',
    description: 'Discover the latest features in Angular and how to use them effectively.',
    imageURL: '../../../assets/images/illustration/ids-illu-comp-general@2x.png',
    buttonOne: 'Explore',
    buttonTwo: 'Watch Video',
  },
  {
    id: 5,
    orientation: 'vertical',
    transparent: true,
    description: 'Discover the latest features in Angular and how to use them effectively.',
  },
] as const;
