export const CONTENTCARD_DATA = [
  {
    // id: 1,
    // variant: 'surface',
    // orientation: 'horizontal',
    // aspectRatio: '16/9',
    // imageBgColorVariant: 'light',
    // imageURL: '../../../assets/images/illustration/ids-illu-comp-general@2x.png',
    // imageCaption: 'this is a caption',
    // overTitle: 'Breaking News',
    // title: 'Angular Best Practices',
    // description: 'Learn how to pass objects properly in Angular!',
    // buttonOne: 'Read More',
    // buttonTwo: 'Subscribe',
    // state: 'do',
    // transparent: true,
    id: 1,
    // eslint-disable-next-line @stylistic/js/max-len
    description: 'If selecting a single option excludes the possibility of choosing any other, a radio component must be used instead of a checkbox component. Do not use the checkbox component in situations where you simply toggle a function on or off.',
    transparent: true,
    orientation: 'horizontal',
  },
  {
    id: 2,
    // eslint-disable-next-line @stylistic/js/max-len
    description: 'We distinguish three states: unchecked, checked, and indeterminate. A „parent” checkbox enters the indeterminate state if at least one child checkbox is in the checked state.',
    title: 'States',
    transparent: true,
    orientation: 'horizontal',
  },
  {
    id: 3,
    orientation: 'vertical',
    aspectRatio: '16/9',
    imageBgColorVariant: 'surface',
    description: '1. container: the element that encompasses all parts of the component.',
    imageURL: '../../../assets/images/component-tn/checkbox-anatomy@2x.png',
    variant: 'surface',
  },
  {
    id: 4,
    orientation: 'horizontal',
    aspectRatio: '16/9',
    imageBgColorVariant: 'light',
    title: '3 variants are in use',
    description: '1. Surface',
    imageURL: '../../../assets/images/component-tn/checkbox-variants@2x.png',
    transparent: true,
  },
  {
    id: 5,
    orientation: 'horizontal',
    aspectRatio: '16/9',
    imageBgColorVariant: 'light',
    title: '4 sizes are in use',
    description: '1. Dense',
    imageURL: '../../../assets/images/component-tn/checkbox-size@2x.png',
    transparent: true,
  },
  {
    id: 6,
    orientation: 'horizontal',
    aspectRatio: '16/9',
    imageBgColorVariant: 'light',
    title: 'Alignment',
    // eslint-disable-next-line @stylistic/js/max-len
    description: 'If selecting a single option excludes the possibility of choosing any other, a radio component must be used instead of a checkbox component. Do not use the checkbox component in situations where you simply toggle a function on or off.',
    imageURL: '../../../assets/images/component-tn/checkbox-alignment-do@2x.png',
    transparent: true,
    state: 'do',
  },
  {
    id: 7,
    orientation: 'horizontal',
    aspectRatio: '16/9',
    imageBgColorVariant: 'light',
    imageURL: '../../../assets/images/component-tn/checkbox-alignment-dont@2x.png',
    transparent: true,
    state: 'dont',
  },
  {
    id: 8,
    orientation: 'horizontal',
    aspectRatio: '16/9',
    imageBgColorVariant: 'surface',
    title: 'As a User....',
    description: '• I should be able to easily understand what each checkbox option represents',
    transparent: true,
  },
  {
    id: 9,
    orientation: 'horizontal',
    aspectRatio: '16/9',
    imageBgColorVariant: 'surface',
    title: 'Labeling',
    description: '• Each checkbox must have a visible label that clearly describes its function or option using the label element.',
    transparent: true,
  },
] as const;
