/* eslint-disable @stylistic/js/max-len */
export const INDEX_DATA = [
  { id: 1,
    title: 'Design tokens',
    description: 'Configuration variables or values in the design system that define visual properties. (e.g. colours, fonts, sizes)',
    imageUrl: '../../../assets/images/tn/ids-token-tn@2x.png',
    imageLink: '#/components/accordion' },
  { id: 2,
    title: 'Foundations',
    description: 'The set of elements and principles that form the basis of a design system. These include typography, colour palette, spacing and basic visual guidelines.',
    imageUrl: '../../../assets/images/tn/ids-foundation-tn@2x.png',
    imageLink: '#/components/action-menu' },
  { id: 3,
    title: 'Components',
    description: 'The building blocks of an application or website that form reusable, self-contained units.',
    imageUrl: '../../../assets/images/tn/ids-components-tn@2x.png',
    imageLink: '#/components/avatar' },
  { id: 4,
    title: 'Patterns',
    description: 'A collection of frequently repeated and best practice patterns and templates to help maintain consistency and a uniform look.',
    imageUrl: '../../../assets/images/tn/ids-patterns-tn@2x.png',
    imageLink: '#/components/button' },
];
