name: Build and Publish Storybook to GitHub Pages

on:
  push:
    branches:
      - 'feature/storybook-deploy-on-github-pages'

permissions:
  contents: read
  pages: write
  id-token: write

# List of jobs
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - id: storybook-build-publish
      uses: bitovi/github-actions-storybook-to-github-pages@v1.0.3
      with:
        checkout: true
        build_command: npm run build:storybook
