name: Build and Publish ids-angular to GitHub Pages

on:
  push:
    branches:
      - "github-pages-demo"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22]

    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Build application
        run: pnpm run build:ci

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: github-pages-demo
          folder: dist/ids-angular/browser
